

NDefines.NGame.DAYS_BEHIND_PAUSE = 60
NDefines.NGame.DAYS_BEHIND_LOWER_SPEED = 30


NDefines.NDiplomacy.MIN_RELATIONS_TO_ALLY = -200
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 12
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.INFILTRATE_ADMINISTRATION_COST = 75
NDefines.NDiplomacy.CHANGE_RIVAL_YEARS = 5
NDefines.NDiplomacy.ABANDON_UNION_PRESTIGE = 0
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_LOSE = 0
NDefines.NDiplomacy.SHAREMAP_PRESTIGE_TRANSFER_GAIN = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_MONTHS = 0
NDefines.NDiplomacy.DISHONORABLE_PEACE_WARSCORE = 0
NDefines.NDiplomacy.DEFENDER_OF_FAITH_TRUST_LOSS = 0
NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 1000
NDefines.NDiplomacy.MARCH_BASE_DEVELOPMENT_CAP = 1000
NDefines.NDiplomacy.SPY_NETWORK_SIEGE_EFFECT = 0.10
NDefines.NDiplomacy.SPY_NETWORK_AE_EFFECT = -0.33
NDefines.NDiplomacy.INTEGRATE_UNION_MIN_YEARS = 40
NDefines.NDiplomacy.INTEGRATE_VASSAL_MIN_YEARS = 5
NDefines.NDiplomacy.MONTHS_BEFORE_TOTAL_OCCUPATION = 6
NDefines.NDiplomacy.GREAT_PROJECT_WARSCORE_COST_MODIFIER = 0
NDefines.NDiplomacy.MAX_ASKED_TRADE_POWER = 100
NDefines.NDiplomacy.UNCONDITIONAL_SURRENDER_MIN_MONTHS = 6
NDefines.NDiplomacy.PEACE_COST_WAR_REPARATIONS = 5
NDefines.NDiplomacy.PEACE_COST_HUMILIATE_RIVAL = 30
NDefines.NDiplomacy.SPY_NETWORK_SIEGE_EFFECT = 0.25
NDefines.NDiplomacy.SPY_NETWORK_AE_EFFECT = -0.4
NDefines.NDiplomacy.SPY_NETWORK_TECH_EFFECT = -0.05
NDefines.NDiplomacy.SPY_NETWORK_TECH_EFFECT_MAX = -0.3
NDefines.NDiplomacy.VASSALIZE_BASE_DEVELOPMENT_CAP = 3000
NDefines.NDiplomacy.MARCH_BASE_DEVELOPMENT_CAP = 3000
NDefines.NDiplomacy.MARCH_DEVELOPMENT_FRACTION = 0.80
NDefines.NDiplomacy.JOIN_HRE_DEVELOPMENT_CAP_VASSAL = 1000



NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.ESTATE_PRIVILEGES_MAX_CONCURRENT = 7
NDefines.NCountry.PIETY_PERCENTAGE_AT_NEW_RULER = 1
NDefines.NCountry.DISINHERIT_PRESTIGE_HIT = -25
NDefines.NCountry.DISINHERIT_PRESTIGE_THRESHOLD = -25
NDefines.NCountry.CONVERSION_COOLDOWN_SECONDARY = 60
NDefines.NCountry.PS_REPLACE_RIVAL = 0
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.MINIMUM_POLICY_TIME = 5
NDefines.NCountry.SELLPROV_PRESTIGE = 0
NDefines.NCountry.CULTURE_COST_DIFF_ADJACENT = -60
NDefines.NCountry.BREAK_VASSAL_PRESTIGE_PENALTY = 0
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 50
NDefines.NCountry.STATE_MAINTENANCE_CULTURE_FACTOR = 0.55
NDefines.NCountry.PS_SET_PRIMARY_CULTURE = 75
NDefines.NCountry.PS_ADD_ACCEPTED_CULTURE = 75
NDefines.NCountry.LIBERTY_DESIRE_GREAT_POWER_VASSAL = 10
NDefines.NCountry.LIBERTY_DESIRE_ROYAL_MARRIAGE = -15
NDefines.NCountry.LIBERTY_DESIRE_SCUTAGE_OFF = 10
NDefines.NCountry.STRENGTHEN_GOVERNMENT_LEGITIMACY = 20
NDefines.NCountry.CALL_ALLY_DECLINE_PRESTIGE_PENALTY = 0
NDefines.NCountry.BREAK_VASSAL_PRESTIGE_PENALTY = 0
NDefines.NCountry.ABANDON_CORE_PRESTIGE = 0
NDefines.NCountry.CORE_LOSE_PRESTIGE = 0
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 7.5
NDefines.NCountry.PS_REMOVE_ACCEPTED_CULTURE = 0
NDefines.NCountry.CULTURE_MIN_DEVELOPMENT_TO_PROMOTE = 5
NDefines.NCountry.STATE_MAINTENANCE_CULTURE_FACTOR = 0.5
NDefines.NCountry.PROSPERITY_INCREASE_SIZE = 2
NDefines.NCountry.ABDICATE_LEGITIMACY_THRESHOLD = 0
NDefines.NCountry.ABDICATE_AGE_THRESHOLD = 30
NDefines.NCountry.ABDICATE_RULING_LENGTH_THRESHOLD = 10
NDefines.NCountry.ABDICATE_LEGITIMACY_HIT = 0
NDefines.NCountry.ABDICATE_PRESTIGE_HIT = -25
NDefines.NCountry.NEW_HEIR_LEGITIMACY_HIT = 0
NDefines.NCountry.NEW_HEIR_LEGITIMACY_THRESHOLD = 0
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_2 = 1			-- Required prestige to to upgrade to government rank 2
NDefines.NCountry.MIN_PRESTIGE_FOR_GOV_RANK_3 = 25
NDefines.NCountry.ESTATE_MIN_DISTRIBUTED_CROWNLAND = 30.5
NDefines.NCountry.ESTATE_AGENDA_ABOUT_TO_EXPIRE_WARNING = 365
NDefines.NCountry.PARLIAMENT_PRESTIGE_HIT = 0
NDefines.NCountry.EXPLORE_COAST_EVENT_CHANCE = 2
NDefines.NCountry.MINIMUM_POLICY_TIME = 1
NDefines.NCountry.MONARCH_DEATH_LEADER_STABILITY_PENALTY = 0
NDefines.NCountry.NAT_FOCUS_YEARS = 5
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.PS_ASSAULT = 0
NDefines.NCountry.PS_ARTILLERY_BARRAGE = 25
NDefines.NCountry.PS_NAVAL_BARRAGE = 15
NDefines.NCountry.PS_MAKE_PROVINCE_CORE = 10
NDefines.NCountry.PS_PROMOTE_MERCANTILISM = 50
NDefines.NCountry.PS_MOVE_CAPITAL_EXTRA = 20
NDefines.NCountry.PS_MOVE_CAPITAL_DISTANCE = 0
NDefines.NCountry.PS_MOVE_CAPITAL_DISTANCE_CAP = 0
NDefines.NCountry.PS_MOVE_TRADE_PORT = 50
NDefines.NCountry.PS_SEIZE_COLONY = 5
NDefines.NCountry.PS_ATTACK_NATIVES = 1
NDefines.NCountry.PS_HARSH_TREATMENT_COST = 50
NDefines.NCountry.PS_GARRISON_SORTIES = 25
NDefines.NCountry.PROVOKE_REVOLT_MIN_PROGRESS = 30.0
NDefines.NCountry.NAVAL_FORCELIMIT_EXTRA_COST_FACTOR = 0.125
NDefines.NCountry.STATE_MAINTENANCE_DEV_FACTOR = 0.008
NDefines.NCountry.STATE_MAINTENANCE_DISTANCE_FACTOR = 0.002
NDefines.NCountry.STATE_MAINTENANCE_CONTINENT_FACTOR = 0.25
NDefines.NCountry.CONVERSION_COOLDOWN_SECONDARY = 0
NDefines.NCountry.NAT_FOCUS_YEARS_RANK = 0
NDefines.NCountry.MAX_TOLERANCE_HERETIC = 8
NDefines.NCountry.MAX_TOLERANCE_HEATHEN = 8
NDefines.NCountry.EXPAND_INFRASTRUCTURE_DEV_LIMIT = 10 
NDefines.NCountry.DEBT_LIMIT_MIL = -999
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 7.5
NDefines.NCountry.EXPLOIT_MIL_MANPOWER = 7.5
NDefines.NCountry.ABANDON_IDEAGROUP_REFUND = 0.75
NDefines.NCountry.MONTHS_TO_CHANGE_CULTURE = 5
NDefines.NCountry.AGE_OF_ADULTHOOD = 14





NDefines.NEconomy.CARAVAN_FACTOR = 3
NDefines.NEconomy.CARAVAN_POWER_MAX = 25
NDefines.NEconomy.CARAVAN_POWER_MIN = 2
NDefines.NEconomy.DEBASE_MAX_CORRUPTION = 25
NDefines.NEconomy.COT_DOWNGRADE_PRESTIGE_COST = 0
NDefines.NEconomy.AUTONOMY_AT_DIPLO_ANNEX = 30
NDefines.NEconomy.AUTONOMY_CHANGE_DURATION = 1825
NDefines.NEconomy.TRADE_COMPANY_STRONG_LIMIT = 0.40
NDefines.NEconomy.TRADE_NON_CAPITAL_OFFICE = 0


NDefines.NMilitary.CAVALRY_SPEED = 1.0
NDefines.NMilitary.WARGOAL_MAX_BONUS = 40
NDefines.NMilitary.DEFAULT_WARGOAL_TICKINGWARSCORE_BONUS = 1.67
NDefines.NMilitary.ARMY_DRILL_YEARLY_DECAY = -0.25
NDefines.NMilitary.MAX_REBEL_SUPPRESSION = 20.0	
NDefines.NMilitary.INF_SUPPRESSION = 0.50			
NDefines.NMilitary.CAV_SUPPRESSION = 1.00	
NDefines.NMilitary.ART_SUPPRESSION = 0.25
NDefines.NMilitary.AREA_REBEL_SUPPRESSION_MULTIPLIER = 5.0
NDefines.NMilitary.RAJPUT_MANPOWER_USAGE = 0.25
NDefines.NMilitary.COSSACKS_MANPOWER_USAGE = 0.25
NDefines.NMilitary.STRELTSY_MANPOWER_USAGE = 0.25
NDefines.NMilitary.RAJPUT_MAXIMUM_RATIO = 4.0
NDefines.NMilitary.COSSACKS_MAXIMUM_RATIO = 3.0
NDefines.NMilitary.RAJPUT_USES_CONSTRUCTION = 1
NDefines.NMilitary.COSSACKS_USES_CONSTRUCTION = 1
NDefines.NMilitary.BACK_LINE_MORALE_DAMAGE_TAKEN_MODIFIER = 0.0
NDefines.NMilitary.BACK_LINE_STRENGTH_DAMAGE_TAKEN_MODIFIER = 0.0
NDefines.NMilitary.TRANSPORT_SHIP_SAILORS_COST = 20
NDefines.NMilitary.TRANSPORT_TIME = 30
NDefines.NMilitary.TRANSPORT_COST = 1
NDefines.NMilitary.MARINE_SHOCK_DAMAGE_TAKEN = -0.10
NDefines.NMilitary.FORTRESS_COST = 0.5
NDefines.NMilitary.SUPPLYLIMIT_BASE_MULTIPLIER = 8.0
NDefines.NMilitary.LOOTED_SCALE = 2
NDefines.NMilitary.LOOTED_MAX = 10
NDefines.NMilitary.MIN_MONTHLY_SAILORS = 10
NDefines.NMilitary.NOMAD_PLAINS_SHOCK_BONUS = 0
NDefines.NMilitary.NOMAD_NON_PLAINS_SHOCK_PENALTY = -0.10
NDefines.NMilitary.SEA_LANDING_PENALTY = -1
NDefines.NMilitary.REBEL_LEADER_POWER = 10
NDefines.NMilitary.DAYS_PER_PHASE = 2
NDefines.NMilitary.WARSCORE_MAX_FROM_BATTLES = 50
NDefines.NMilitary.FORT_FLIPPING_TIME = 15
NDefines.NMilitary.STACKWIPE_MANPOWER_RETURN_FRACTION = 0.4
NDefines.NMilitary.LEADER_GAIN_PERSONALITY_BASE_CHANCE = 25.0
NDefines.NMilitary.SUPPLY_DEPOT_MIL_COST = 0
NDefines.NMilitary.NAVAL_DOCTRINE_SAILORS_COST = 0.05			-- Cost for switching naval doctrine (Share of sailors)
NDefines.NMilitary.NAVAL_DOCTRINE_MIN_FORCE_LIMIT = 15
NDefines.NMilitary.CREATE_HUSSARS_MIL_COST = 0
NDefines.NMilitary.HUSSARS_BASE_COST_MODIFIER = 1.0
NDefines.NMilitary.HUSSARS_MANPOWER_COST_MODIFIER = 1.0
NDefines.NMilitary.HUSSARS_STARTING_STRENGTH = 1.0
NDefines.NMilitary.HUSSARS_STARTING_MORALE = 0.15
NDefines.NMilitary.HUSSARS_USES_CONSTRUCTION = 1
NDefines.NMilitary.NAVAL_BASE_ENGAGEMENT_WIDTH = 30
NDefines.NMilitary.NAVAL_CASUALTY_MIN_MORALE_DAMAGE = 0.05




NDefines.NAI.DIPLOMATIC_ACTION_VASSALIZE_DEVELOPMENT_FACTOR = 5



NDefines.NReligion.MAX_CHURCH_POWER = 350
NDefines.NReligion.MIN_HARMONIZE_DEVELOPMENT = 20
NDefines.NReligion.STARTING_HARMONY = 50.0
NDefines.NReligion.YEARLY_HARMONY_INCREASE = 2.0
NDefines.NReligion.HARMONY_LOSS_PER_DEV_CONVERTED = 0
NDefines.NReligion.YEARLY_HARMONY_INCREASE_WHEN_HARMONIZING = -5.0
NDefines.NReligion.YEARLY_HARMONIZATION_PROGRESS = 0.05
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = 0
NDefines.NReligion.MIN_CARDINALS = 15										-- Least amount of cardinals/ Starting cardinals
NDefines.NReligion.MAX_CARDINALS = 120
NDefines.NReligion.MAX_CARDINALS_PER_COUNTRY = 30
NDefines.NReligion.YEARLY_POPE_INVESTED_INFLUENCE_PER_CARDINAL = 0
NDefines.NReligion.MAX_PAPAL_INFLUENCE = 999								-- The maximum stored amount of papal influence for each country.
NDefines.NReligion.REFORM_DESIRE_PER_YEAR = 0.005
NDefines.NReligion.INVEST_PAPAL_INFLUENCE = 20.0
NDefines.NReligion.CHANGE_SECONDARY_PRESTIGE_HIT = 0
NDefines.NReligion.CALL_ECUMENICAL_COUNCIL_COST = 100



NDefines.NGovernment.EXPAND_INFRASTRUCTURE_ADM_COST = 25
NDefines.NGovernment.GOVERNMENT_REFORM_CHANGE_PROGRESS_COST = 25.0
NDefines.NGovernment.GOVERNMENT_REFORM_COST_CENTRALIZE_STATE = 20.0
NDefines.NGovernment.CENTRALIZE_STATE_YEARS = 2.5
NDefines.NGovernment.EXPAND_ADMIN_COST = 250.0
NDefines.NGovernment.LEADER_AS_MONARCH_TRADITION = 100
NDefines.NGovernment.CONCENTRATE_DEVELOPMENT_CAPITAL_PROPORTION = 0.5